version: "3.9"

# services:
#   db:
#     container_name: db
#     image: postgres:latest
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=postgres
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: {}

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mypassword # Set your desired password here
    volumes: pgdata:/var/lib/postgresql/data # Persist data using a volume

ports:
  - "5432:5432" # Map container port 5432 to host port 5432

volumes:
  pgdata:
